// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: aite.proto

// Package aite implements a disruptive service which can manipulate resources
// within a KNE pod.
//
// It is named after Aite (Até) the green goddess of mischief, delusion and ruin.

package aite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InterfaceStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the interface that is to be manipulated.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// If set to true, the interface should be set to administratively down.
	Shutdown bool `protobuf:"varint,2,opt,name=shutdown,proto3" json:"shutdown,omitempty"`
}

func (x *InterfaceStateRequest) Reset() {
	*x = InterfaceStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStateRequest) ProtoMessage() {}

func (x *InterfaceStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStateRequest.ProtoReflect.Descriptor instead.
func (*InterfaceStateRequest) Descriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{0}
}

func (x *InterfaceStateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStateRequest) GetShutdown() bool {
	if x != nil {
		return x.Shutdown
	}
	return false
}

type InterfaceStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *InterfaceStateResponse) Reset() {
	*x = InterfaceStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStateResponse) ProtoMessage() {}

func (x *InterfaceStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStateResponse.ProtoReflect.Descriptor instead.
func (*InterfaceStateResponse) Descriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{1}
}

type ImpairInterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the interface that is to be manipulated.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// When specified, adds additional latency to packets traversing the interface.
	LatencyMsec uint32 `protobuf:"varint,2,opt,name=latency_msec,json=latencyMsec,proto3" json:"latency_msec,omitempty"`
	// When specified, adds loss with the specified percentage to packets traversing
	// the interface.
	LossPct uint32 `protobuf:"varint,3,opt,name=loss_pct,json=lossPct,proto3" json:"loss_pct,omitempty"`
}

func (x *ImpairInterfaceRequest) Reset() {
	*x = ImpairInterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImpairInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpairInterfaceRequest) ProtoMessage() {}

func (x *ImpairInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpairInterfaceRequest.ProtoReflect.Descriptor instead.
func (*ImpairInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{2}
}

func (x *ImpairInterfaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ImpairInterfaceRequest) GetLatencyMsec() uint32 {
	if x != nil {
		return x.LatencyMsec
	}
	return 0
}

func (x *ImpairInterfaceRequest) GetLossPct() uint32 {
	if x != nil {
		return x.LossPct
	}
	return 0
}

type ImpairInterfaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImpairInterfaceResponse) Reset() {
	*x = ImpairInterfaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aite_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImpairInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImpairInterfaceResponse) ProtoMessage() {}

func (x *ImpairInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aite_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImpairInterfaceResponse.ProtoReflect.Descriptor instead.
func (*ImpairInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{3}
}

var File_aite_proto protoreflect.FileDescriptor

var file_aite_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1a, 0x6e, 0x65,
	0x74, 0x5f, 0x73, 0x64, 0x6e, 0x5f, 0x64, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x2e, 0x61, 0x69, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x15, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6f, 0x77,
	0x6e, 0x22, 0x18, 0x0a, 0x16, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6a, 0x0a, 0x16, 0x49,
	0x6d, 0x70, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x74,
	0x65, 0x6e, 0x63, 0x79, 0x5f, 0x6d, 0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0b, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x73, 0x65, 0x63, 0x12, 0x19, 0x0a, 0x08,
	0x6c, 0x6f, 0x73, 0x73, 0x5f, 0x70, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07,
	0x6c, 0x6f, 0x73, 0x73, 0x50, 0x63, 0x74, 0x22, 0x19, 0x0a, 0x17, 0x49, 0x6d, 0x70, 0x61, 0x69,
	0x72, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x32, 0xfb, 0x01, 0x0a, 0x04, 0x41, 0x69, 0x74, 0x65, 0x12, 0x77, 0x0a, 0x0e, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x31, 0x2e,
	0x6e, 0x65, 0x74, 0x5f, 0x73, 0x64, 0x6e, 0x5f, 0x64, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61,
	0x6c, 0x69, 0x7a, 0x65, 0x64, 0x2e, 0x61, 0x69, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x32, 0x2e, 0x6e, 0x65, 0x74, 0x5f, 0x73, 0x64, 0x6e, 0x5f, 0x64, 0x65, 0x63, 0x65, 0x6e,
	0x74, 0x72, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x2e, 0x61, 0x69, 0x74, 0x65, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7a, 0x0a, 0x0f, 0x49, 0x6d, 0x70, 0x61, 0x69, 0x72, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x32, 0x2e, 0x6e, 0x65, 0x74, 0x5f, 0x73, 0x64,
	0x6e, 0x5f, 0x64, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x64, 0x2e,
	0x61, 0x69, 0x74, 0x65, 0x2e, 0x49, 0x6d, 0x70, 0x61, 0x69, 0x72, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x33, 0x2e, 0x6e, 0x65,
	0x74, 0x5f, 0x73, 0x64, 0x6e, 0x5f, 0x64, 0x65, 0x63, 0x65, 0x6e, 0x74, 0x72, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x64, 0x2e, 0x61, 0x69, 0x74, 0x65, 0x2e, 0x49, 0x6d, 0x70, 0x61, 0x69, 0x72, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x72,
	0x6f, 0x62, 0x73, 0x68, 0x61, 0x6b, 0x69, 0x72, 0x2f, 0x61, 0x69, 0x74, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69, 0x74, 0x65, 0x3b, 0x61, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aite_proto_rawDescOnce sync.Once
	file_aite_proto_rawDescData = file_aite_proto_rawDesc
)

func file_aite_proto_rawDescGZIP() []byte {
	file_aite_proto_rawDescOnce.Do(func() {
		file_aite_proto_rawDescData = protoimpl.X.CompressGZIP(file_aite_proto_rawDescData)
	})
	return file_aite_proto_rawDescData
}

var file_aite_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_aite_proto_goTypes = []interface{}{
	(*InterfaceStateRequest)(nil),   // 0: net_sdn_decentralized.aite.InterfaceStateRequest
	(*InterfaceStateResponse)(nil),  // 1: net_sdn_decentralized.aite.InterfaceStateResponse
	(*ImpairInterfaceRequest)(nil),  // 2: net_sdn_decentralized.aite.ImpairInterfaceRequest
	(*ImpairInterfaceResponse)(nil), // 3: net_sdn_decentralized.aite.ImpairInterfaceResponse
}
var file_aite_proto_depIdxs = []int32{
	0, // 0: net_sdn_decentralized.aite.Aite.InterfaceState:input_type -> net_sdn_decentralized.aite.InterfaceStateRequest
	2, // 1: net_sdn_decentralized.aite.Aite.ImpairInterface:input_type -> net_sdn_decentralized.aite.ImpairInterfaceRequest
	1, // 2: net_sdn_decentralized.aite.Aite.InterfaceState:output_type -> net_sdn_decentralized.aite.InterfaceStateResponse
	3, // 3: net_sdn_decentralized.aite.Aite.ImpairInterface:output_type -> net_sdn_decentralized.aite.ImpairInterfaceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aite_proto_init() }
func file_aite_proto_init() {
	if File_aite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImpairInterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aite_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImpairInterfaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aite_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aite_proto_goTypes,
		DependencyIndexes: file_aite_proto_depIdxs,
		MessageInfos:      file_aite_proto_msgTypes,
	}.Build()
	File_aite_proto = out.File
	file_aite_proto_rawDesc = nil
	file_aite_proto_goTypes = nil
	file_aite_proto_depIdxs = nil
}
