// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: aite.proto

// Package aite implements a disruptive service which can manipulate resources
// within a KNE pod.
//
// It is named after Aite (Até) the Greek goddess of mischief, delusion and ruin.

package aite

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InterfaceState specifies the state that an interface should be placed into.
type InterfaceState int32

const (
	// Invalid zero value.
	InterfaceState_IS_UNSPECIFIED InterfaceState = 0
	// The interface should be administratively and operationally up.
	InterfaceState_IS_UP InterfaceState = 1
	// The interface should be administratively down.
	InterfaceState_IS_ADMIN_DOWN InterfaceState = 2
)

// Enum value maps for InterfaceState.
var (
	InterfaceState_name = map[int32]string{
		0: "IS_UNSPECIFIED",
		1: "IS_UP",
		2: "IS_ADMIN_DOWN",
	}
	InterfaceState_value = map[string]int32{
		"IS_UNSPECIFIED": 0,
		"IS_UP":          1,
		"IS_ADMIN_DOWN":  2,
	}
)

func (x InterfaceState) Enum() *InterfaceState {
	p := new(InterfaceState)
	*p = x
	return p
}

func (x InterfaceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterfaceState) Descriptor() protoreflect.EnumDescriptor {
	return file_aite_proto_enumTypes[0].Descriptor()
}

func (InterfaceState) Type() protoreflect.EnumType {
	return &file_aite_proto_enumTypes[0]
}

func (x InterfaceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterfaceState.Descriptor instead.
func (InterfaceState) EnumDescriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{0}
}

type SetInterfaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Name of the interface that is to be manipulated.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Declarative set of parameters that the interface should be configured
	// with.
	Params *InterfaceStateParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *SetInterfaceRequest) Reset() {
	*x = SetInterfaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aite_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInterfaceRequest) ProtoMessage() {}

func (x *SetInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aite_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInterfaceRequest.ProtoReflect.Descriptor instead.
func (*SetInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{0}
}

func (x *SetInterfaceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetInterfaceRequest) GetParams() *InterfaceStateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type InterfaceStateParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The state that the interface should be in at the end of the state
	// transition. This field must be specified.
	State InterfaceState `protobuf:"varint,1,opt,name=state,proto3,enum=openconfig.aite.InterfaceState" json:"state,omitempty"`
	// When specified, adds additional latency to packets traversing the interface.
	// If set to the zero value, no additional latency is added.
	LatencyMsec uint32 `protobuf:"varint,2,opt,name=latency_msec,json=latencyMsec,proto3" json:"latency_msec,omitempty"`
	// When specified, adds loss with the specified percentage to packets traversing
	// the interface. If set to the zero value, zero loss is injected.
	LossPct uint32 `protobuf:"varint,3,opt,name=loss_pct,json=lossPct,proto3" json:"loss_pct,omitempty"`
}

func (x *InterfaceStateParams) Reset() {
	*x = InterfaceStateParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aite_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InterfaceStateParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStateParams) ProtoMessage() {}

func (x *InterfaceStateParams) ProtoReflect() protoreflect.Message {
	mi := &file_aite_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStateParams.ProtoReflect.Descriptor instead.
func (*InterfaceStateParams) Descriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{1}
}

func (x *InterfaceStateParams) GetState() InterfaceState {
	if x != nil {
		return x.State
	}
	return InterfaceState_IS_UNSPECIFIED
}

func (x *InterfaceStateParams) GetLatencyMsec() uint32 {
	if x != nil {
		return x.LatencyMsec
	}
	return 0
}

func (x *InterfaceStateParams) GetLossPct() uint32 {
	if x != nil {
		return x.LossPct
	}
	return 0
}

// InterfaceStateResponse returns the intended state of the interface once an
// interface state request has been accepted.
type SetInterfaceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Params *InterfaceStateParams `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
}

func (x *SetInterfaceResponse) Reset() {
	*x = SetInterfaceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aite_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInterfaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInterfaceResponse) ProtoMessage() {}

func (x *SetInterfaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aite_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInterfaceResponse.ProtoReflect.Descriptor instead.
func (*SetInterfaceResponse) Descriptor() ([]byte, []int) {
	return file_aite_proto_rawDescGZIP(), []int{2}
}

func (x *SetInterfaceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetInterfaceResponse) GetParams() *InterfaceStateParams {
	if x != nil {
		return x.Params
	}
	return nil
}

var File_aite_proto protoreflect.FileDescriptor

var file_aite_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x69, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6f, 0x70,
	0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x69, 0x74, 0x65, 0x22, 0x68, 0x0a,
	0x13, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x69, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52,
	0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x8b, 0x01, 0x0a, 0x14, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x12, 0x35, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1f, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x69, 0x74,
	0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x6c, 0x61, 0x74, 0x65, 0x6e,
	0x63, 0x79, 0x5f, 0x6d, 0x73, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x6c,
	0x61, 0x74, 0x65, 0x6e, 0x63, 0x79, 0x4d, 0x73, 0x65, 0x63, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f,
	0x73, 0x73, 0x5f, 0x70, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x6c, 0x6f,
	0x73, 0x73, 0x50, 0x63, 0x74, 0x22, 0x69, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65,
	0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x3d, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x25, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61,
	0x69, 0x74, 0x65, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x2a, 0x42, 0x0a, 0x0e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x49, 0x53, 0x5f, 0x55, 0x50, 0x10,
	0x01, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x53, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x5f, 0x44, 0x4f,
	0x57, 0x4e, 0x10, 0x02, 0x32, 0x63, 0x0a, 0x04, 0x41, 0x69, 0x74, 0x65, 0x12, 0x5b, 0x0a, 0x0c,
	0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x12, 0x24, 0x2e, 0x6f,
	0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x61, 0x69, 0x74, 0x65, 0x2e, 0x53,
	0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e,
	0x61, 0x69, 0x74, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2f, 0x61, 0x69, 0x74, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69,
	0x74, 0x65, 0x3b, 0x61, 0x69, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aite_proto_rawDescOnce sync.Once
	file_aite_proto_rawDescData = file_aite_proto_rawDesc
)

func file_aite_proto_rawDescGZIP() []byte {
	file_aite_proto_rawDescOnce.Do(func() {
		file_aite_proto_rawDescData = protoimpl.X.CompressGZIP(file_aite_proto_rawDescData)
	})
	return file_aite_proto_rawDescData
}

var file_aite_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aite_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_aite_proto_goTypes = []interface{}{
	(InterfaceState)(0),          // 0: openconfig.aite.InterfaceState
	(*SetInterfaceRequest)(nil),  // 1: openconfig.aite.SetInterfaceRequest
	(*InterfaceStateParams)(nil), // 2: openconfig.aite.InterfaceStateParams
	(*SetInterfaceResponse)(nil), // 3: openconfig.aite.SetInterfaceResponse
}
var file_aite_proto_depIdxs = []int32{
	2, // 0: openconfig.aite.SetInterfaceRequest.params:type_name -> openconfig.aite.InterfaceStateParams
	0, // 1: openconfig.aite.InterfaceStateParams.state:type_name -> openconfig.aite.InterfaceState
	2, // 2: openconfig.aite.SetInterfaceResponse.params:type_name -> openconfig.aite.InterfaceStateParams
	1, // 3: openconfig.aite.Aite.SetInterface:input_type -> openconfig.aite.SetInterfaceRequest
	3, // 4: openconfig.aite.Aite.SetInterface:output_type -> openconfig.aite.SetInterfaceResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_aite_proto_init() }
func file_aite_proto_init() {
	if File_aite_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aite_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInterfaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aite_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InterfaceStateParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aite_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInterfaceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aite_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aite_proto_goTypes,
		DependencyIndexes: file_aite_proto_depIdxs,
		EnumInfos:         file_aite_proto_enumTypes,
		MessageInfos:      file_aite_proto_msgTypes,
	}.Build()
	File_aite_proto = out.File
	file_aite_proto_rawDesc = nil
	file_aite_proto_goTypes = nil
	file_aite_proto_depIdxs = nil
}
